### ISSUE TITLE
Can not run this repository

### ISSUE THREAD

**Issue by binhle2001** [Askill/Video-Synopsis#1]
I encountered the following situation when running this repo. The terminal displayed the code below and remained the same for over 2 hours without any change. I don't know the reason for this issue, can you support me?
Current Config:
min_area:               300
max_area:               900000
threshold:              7
resizeWidth:            700
inputPath:              20240601_093007.mp4
outputPath:             output
maxLayerLength:         5000
minLayerLength:         40
tolerance:              20
maxLength:              None
ttolerance:             50
videoBufferLength:              250
LayersPerContour:               220
avgNum:         10
ContourExtractor initiated
  0.01 % processed in 0.99s

**Comment by Askill** [comment]
Hej there, 
full transparency, I wrote this in Uni and haven't really looked at it again, there is a pdf in german that explains how everything works, you would need to translate that...

I assume there is too much movement found, although there should be at least some minor progress... do you have a screenshot from the video you're processing that you can share? And have you tried a shorter / different video?
